spring.application.name=jutjubic-backend

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.profiles.active=local
spring.config.import=optional:application-local.properties
spring.jpa.open-in-view=false


app.jwt.secret=
app.jwt.expiration-ms=86400000

logging.level.org.springframework.cache=DEBUG


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jackson.serialization.write-dates-as-timestamps=false






